version: 2.1
jobs:
  build:
    branches:
      only:
        - main
    docker:
      - image: circleci/node:16.13.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
    - run:
          name: Build
          command: |
            npm run build
    - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
    - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./build --prod
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main